- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v4
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # Adicione esse token nos secrets do repo
    files: target/site/jacoco/jacoco.xml
